---
default_stages: [commit, manual]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
        description: Makes sure files end in a newline and only a newline.
      - id: trailing-whitespace
        description: Trims trailing whitespace
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: check-case-conflict
        description: Checks for files that would conflict in case-insensitive filesystems.
      - id: check-merge-conflict
        description: Checks for files that contain merge conflict strings
      - id: no-commit-to-branch
        args: [--branch, main]
        description: Protect specific branches from direct checkins.
      - id: detect-private-key
        description: Detects the presence of private keys.
      - id: detect-private-key
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        entry: codespell --ignore-words ignore-spelling-words.txt --skip="cspell.json"
        description: Spell checker
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        description: Run shellcheck against scripts
        args: ["--severity=warning"]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
        description: Validate commit message aligns with expected conventions
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
  # TODO: some java quality check
