---

name: Detect Secrets & Passwords

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

# cancel any previously-started, yet still active runs of this workflow on the same branch
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-detect-secrets:
    name: Call Detect Secrets
    # remember about username
    uses: asmaestro/actions/.github/workflows/detect-secrets.yaml@main
    permissions:
      pull-requests: write
      contents: read