---
name: IaC Validation

on:
  pull_request:
    paths:
      - 'kubernetes/**'
      - 'Dockerfile'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  iac:
    name: Validate IaC
    uses: asmaestro/actions/.github/workflows/iac-scan-trivy.yaml@solution-security
    with:
      exit-code: 1 # fail the job if issues are found
      severity: HIGH,CRITICAL
      ignore-unfixed: true
      format: table
      upload-artifact: true
      upload-release-assets: false
      upload-results-github-security: false
